export const codeToDesc: Record<WwoCode, WeatherDesc> = {
  113: "Sunny",
  116: "PartlyCloudy",
  119: "Cloudy",
  122: "VeryCloudy",
  143: "Fog",
  176: "LightShowers",
  179: "LightSleetShowers",
  182: "LightSleet",
  185: "LightSleet",
  200: "ThunderyShowers",
  227: "LightSnow",
  230: "HeavySnow",
  248: "Fog",
  260: "Fog",
  263: "LightShowers",
  266: "LightRain",
  281: "LightSleet",
  284: "LightSleet",
  293: "LightRain",
  296: "LightRain",
  299: "HeavyShowers",
  302: "HeavyRain",
  305: "HeavyShowers",
  308: "HeavyRain",
  311: "LightSleet",
  314: "LightSleet",
  317: "LightSleet",
  320: "LightSnow",
  323: "LightSnowShowers",
  326: "LightSnowShowers",
  329: "HeavySnow",
  332: "HeavySnow",
  335: "HeavySnowShowers",
  338: "HeavySnow",
  350: "LightSleet",
  353: "LightShowers",
  356: "HeavyShowers",
  359: "HeavyRain",
  362: "LightSleetShowers",
  365: "LightSleetShowers",
  368: "LightSnowShowers",
  371: "HeavySnowShowers",
  374: "LightSleetShowers",
  377: "LightSleet",
  386: "ThunderyShowers",
  389: "ThunderyHeavyRain",
  392: "ThunderySnowShowers",
  395: "HeavySnowShowers",
};

export const descToStatus: Record<WeatherDesc, WeatherStatus> = {
  Unknown: "unknown",
  Cloudy: "cloudy",
  Fog: "fog",
  HeavyRain: "rain",
  HeavyShowers: "rain",
  HeavySnow: "snow",
  HeavySnowShowers: "snow",
  LightRain: "chancerain",
  LightShowers: "chancerain",
  LightSleet: "chancesleet",
  LightSleetShowers: "chancesleet",
  LightSnow: "chancesnow",
  LightSnowShowers: "chancesnow",
  PartlyCloudy: "partlycloudy",
  Sunny: "sunny",
  ThunderyHeavyRain: "tstorms",
  ThunderyShowers: "tstorms",
  ThunderySnowShowers: "tstorms",
  VeryCloudy: "cloudy",
};

export const statusToFavicon: Record<WeatherStatus, Favicon> = {
  chanceflurries: "Cloud with Snow.ico",
  chancerain: "Sun Behind Rain Cloud.ico",
  chancesleet: "Cloud with Snow.ico",
  chancesnow: "Cloud with Snow.ico",
  chancetstorms: "Cloud with Lightning.ico",
  clear: "Sun.ico",
  cloudy: "Sun Behind Large Cloud.ico",
  flurries: "Snowflake.ico",
  fog: "Fog.ico",
  hazy: "Fog.ico",
  mostlycloudy: "Sun Behind Cloud.ico",
  mostlysunny: "Sun Behind Small Cloud.ico",
  partlycloudy: "Sun Behind Small Cloud.ico",
  partlysunny: "Sun Behind Cloud.ico",
  rain: "Umbrella with Rain Drops.ico",
  sleet: "Umbrella with Rain Drops.ico",
  snow: "Snowflake.ico",
  sunny: "Sun.ico",
  tstorms: "Cloud with Lightning and Rain.ico",
  unknown: "Umbrella.ico",
};

export const phaseToFavicon: Record<MoonPhase, Favicon> = {
  "New Moon": "New Moon.ico",
  "Waxing Crescent": "Waxing Crescent Moon.ico",
  "First Quarter": "First Quarter Moon.ico",
  "Waxing Gibbous": "Waxing Gibbous Moon.ico",
  "Full Moon": "Full Moon.ico",
  "Waning Gibbous": "Waning Gibbous Moon.ico",
  "Last Quarter": "Last Quarter Moon.ico",
  "Waning Crescent": "Waning Crescent Moon.ico",
};
